// <auto-generated />
using Kodlama.io.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kodlama.io.Persistance.Migrations
{
    [DbContext(typeof(KodlamaIoContext))]
    [Migration("20240412134448_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kodlama.io.Domain.Entities.ProgramLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ProgramLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "java"
                        });
                });

            modelBuilder.Entity("Kodlama.io.Domain.Entities.ProgramLanguageTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("ProgramLanguageId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramLanguageId");

                    b.HasKey("Id");

                    b.HasIndex("ProgramLanguageId");

                    b.ToTable("ProgramLanguageTechnologies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "entityFramework",
                            ProgramLanguageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "spring Boot",
                            ProgramLanguageId = 2
                        });
                });

            modelBuilder.Entity("Kodlama.io.Domain.Entities.ProgramLanguageTechnology", b =>
                {
                    b.HasOne("Kodlama.io.Domain.Entities.ProgramLanguage", "ProgramLanguage")
                        .WithMany("ProgramLanguageTechnology")
                        .HasForeignKey("ProgramLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramLanguage");
                });

            modelBuilder.Entity("Kodlama.io.Domain.Entities.ProgramLanguage", b =>
                {
                    b.Navigation("ProgramLanguageTechnology");
                });
#pragma warning restore 612, 618
        }
    }
}
